"use client";

import dynamic from "next/dynamic";
import Image from "next/image";
import { motion, useScroll, useTransform } from "framer-motion";
import { useState } from "react";
import { Activity, ArrowRight, Brain, Check, ChevronDown, CircleDot, Dna, Droplets, FlaskConical, HeartPulse, Leaf, Menu, Microscope, ShieldPlus, Sparkles, Sun, X, Zap } from "lucide-react";

const MoleculeScene = dynamic(() => import("./MoleculeScene"), { ssr: false });
const nav = [["Home","home"],["Why Nitric Oxide?","why-no"],["Technology","technology"],["Benefits","benefits"],["Science","science"],["Research Team","team"],["Product","product"],["FAQ","faq"],["Contact","contact"]];
const researchers = [
  ["Dr. Cheon Hyun Soo","SunChon National University","Head of BIO N:OV Medical Development & Research Board","researcher-cheon.png"],
  ["Prof. Dr. Hyun-Ock Pae","Wonkwang University, School of Medicine","Research in nitric oxide and metabolites","researcher-pae.png"],
  ["Ph.D. Min Sun Kim","Wonkwang University School of Medicine","Research in cardiovascular health","researcher-min.png"],
  ["Prof. Dr. Yong-Il Shin","Pusan National University, School of Medicine","Research in neuro-rehabilitation","researcher-shin.png"],
  ["Dr. Ju Sung-Min","Center of TKM, Wonkwang University","Research in nitric oxide and physiological systems","researcher-ju.png"],
  ["Ass. Prof. A-Lum Han","University Hospital of Wonkwang","Research in metabolic health and clinical nutrition","researcher-han.png"],
  ["Prof. Dr. Kim Jong-Suk","Jeonbuk National University Medical School","Research in nitric oxide and body metabolism","researcher-kim.png"],
  ["Dr. Sooah Kim","College of Medical Science, Jeonju University","Research in regenerative medicine and food application","researcher-sooah.png"]
];
const pillars = [
  ["Circulatory Wellness","Designed to support normal blood-vessel function as part of everyday wellbeing.",HeartPulse],
  ["Metabolic Wellness","A wellness-focused formula intended to complement balanced nutrition and healthy routines.",Activity],
  ["Everyday Vitality","Supports an active lifestyle and the body’s normal energy-related processes.",Zap],
  ["Healthy Ageing","Created for everyday wellness habits throughout adulthood.",Dna],
  ["Skin Wellness","Helps support a whole-body wellness routine that includes healthy skin care.",Sparkles]
];

function Reveal({ children, className="", id }: { children: React.ReactNode; className?: string; id?: string }) {
  return <motion.section id={id} className={className} initial={{ opacity: 0, y: 34 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: .7, ease: [.2,.8,.2,1] }}>{children}</motion.section>;
}
function Heading({eyebrow,title,copy,light=false}:{eyebrow:string;title:string;copy?:string;light?:boolean}) { return <div className="heading"><span className="eyebrow">{eyebrow}</span><h2 className={light?"text-white":""}>{title}</h2>{copy&&<p className={light?"text-blue-100":""}>{copy}</p>}</div> }

export default function BioNovSite({faq}:{faq:{question:string;answer:string}[]}) {
  const [menu,setMenu]=useState(false); const [tab,setTab]=useState(0); const [openFaq,setOpenFaq]=useState(0);
  const { scrollYProgress }=useScroll(); const productY=useTransform(scrollYProgress,[0,.35],[0,80]);
  return <main className="overflow-hidden">
    <header className="nav-shell"><a href="#home" className="brand" aria-label="BIO N:OV home"><span className="brand-mark">V</span><span>BIO N:OV</span></a><nav className="desktop-nav">{nav.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><a className="nav-cta" href="#contact">Contact us <ArrowRight size={15}/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button>{menu&&<div className="mobile-nav">{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</div>}</header>

    <section id="home" className="hero">
      <div className="orb orb-a"/><div className="orb orb-b"/><div className="particles"/>
      <div className="hero-copy"><span className="hero-kicker"><CircleDot size={14}/> Fermentation-based wellness science</span><h1>BIO N:OV</h1><h2>Clearing the Way<br/>to <span>Optimum Health</span></h2><p>A next-generation wellness formula developed using microbial fermentation technology to support nitric oxide generation and everyday wellbeing.</p><div className="hero-actions"><a className="button primary" href="#product">Discover BIO N:OV <ArrowRight size={18}/></a><a className="button glass" href="#science">Explore the Science</a></div><small>Information on this website is for educational purposes only and is not intended to diagnose, treat, cure or prevent any disease.</small></div>
      <motion.div className="hero-product" style={{y:productY}} whileHover={{rotateY:5,rotateX:-2}}><div className="product-halo"/><Image src="/images/bio-nov-hero.jpg" alt="BIO N:OV product box, blister pack and tablets" width={1920} height={1080} priority /></motion.div>
      <a href="#why-no" className="scroll-cue">Scroll to discover <ChevronDown/></a>
    </section>

    <Reveal id="why-no" className="section molecule-section"><Heading eyebrow="The molecule within" title="Why Nitric Oxide Matters" copy="Nitric oxide is a naturally occurring signalling molecule involved in several normal biological processes. Research context and market-specific wording should be verified before publication."/><div className="molecule-grid"><div className="molecule-canvas"><MoleculeScene/></div><div className="benefit-orbit">{[["Circulation",Droplets],["Vitality",Zap],["Cognition",Brain],["Metabolic Support",Activity],["Immune Function",ShieldPlus]].map(([x,Icon])=><motion.div whileHover={{y:-6}} className="mini-card" key={x as string}><Icon/><span>{x as string}</span></motion.div>)}</div></div><div className="source-note">Scientific source placeholder: add legally approved primary references for each educational statement.</div></Reveal>

    <Reveal className="section age" id="science"><Heading eyebrow="A natural life-course change" title="Nitric Oxide Production Changes with Age" copy="Natural nitric oxide production may decline with age. The illustration is educational and does not predict an individual outcome."/><div className="chart"><svg viewBox="0 0 1000 320" role="img" aria-label="Illustrative declining trend from the twenties to age sixty plus"><defs><linearGradient id="line" x1="0" x2="1"><stop stopColor="#12bdf3"/><stop offset=".55" stopColor="#7367ec"/><stop offset="1" stopColor="#f24ea6"/></linearGradient></defs><motion.path d="M70 62 C 245 70, 310 98, 410 124 S 620 182, 720 215 S 870 258, 940 266" fill="none" stroke="url(#line)" strokeWidth="10" strokeLinecap="round" initial={{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true}} transition={{duration:2}}/>{[70,270,470,670,870].map((x,i)=><g key={x}><circle cx={x} cy={[62,92,140,198,250][i]} r="12" fill="#fff" stroke="#206ddd" strokeWidth="6"/><text x={x} y="305" textAnchor="middle">{["20s","30s","40s","50s","60+"][i]}</text></g>)}</svg></div></Reveal>

    <Reveal className="body-section"><div className="body-copy"><Heading light eyebrow="Interactive body atlas" title="One Signal. Many Biological Roles." copy="Select a system to explore how nitric oxide participates in normal functions."/><div className="body-list">{[["Brain","Cellular signalling and processes linked with normal cognition."],["Respiratory system","Signalling pathways within normal respiratory physiology."],["Heart","Normal vascular signalling that supports circulation."],["Circulatory system","Vasodilation signalling that helps blood vessels relax."],["Digestive system","Cell communication within normal digestive physiology."],["Immune system","Signalling involved in normal immune responses."]].map(([a,b],i)=><motion.button whileHover={{x:6}} key={a}><span>{String(i+1).padStart(2,"0")}</span><div><b>{a}</b><small>{b}</small></div></motion.button>)}</div></div><div className="body-visual"><Image src="/images/body-systems.png" alt="Medical illustration of body systems" width={1920} height={1080}/><div className="scanline"/></div></Reveal>

    <Reveal className="section"><Heading eyebrow="Everyday foundations" title="Supporting Your Body’s Natural Nitric Oxide Pathways" copy="BIO N:OV is designed as a convenient wellness product. It does not replace exercise, a balanced diet or medical care."/><div className="lifestyle-path">{[["Regular physical activity","Movement supports overall cardiovascular wellbeing.",Activity],["Balanced nutrition","A varied diet provides nutrients for normal body functions.",Leaf],["Healthy sunlight exposure","Appropriate daylight supports normal daily rhythms.",Sun]].map(([a,b,Icon])=><div className="lifestyle" key={a as string}><Icon/><h3>{a as string}</h3><p>{b as string}</p></div>)}<div className="path-line"/><div className="product-node"><span>V</span><b>BIO N:OV</b><small>Convenient wellness support</small></div></div></Reveal>

    <Reveal id="technology" className="section tech"><Heading eyebrow="Evolution of formulation" title="Technology Roadmap" copy="A simple overview inspired by the PDF. Comparative performance claims have intentionally been excluded pending approved evidence."/><div className="timeline">{[["01","First Generation","Arginine-Based Formulas"],["02","Second Generation","Vegetable and Fruit Extracts"],["03","Third Generation","BIO N:OV Microbial Fermentation Technology"]].map((x,i)=><motion.div whileHover={{y:-8}} className={`timeline-card ${i===2?"active":""}`} key={x[0]}><span>{x[0]}</span>{i===2?<FlaskConical/>:<Microscope/>}<h3>{x[1]}</h3><p>{x[2]}</p>{i===2&&<div className="bubbles">{[1,2,3,4,5].map(n=><i key={n}/>)}</div>}</motion.div>)}</div><div className="tech-note"><Check/> BIO N:OV uses a fermentation-based approach and naturally derived ingredients.</div></Reveal>

    <Reveal className="ingredients section"><Heading eyebrow="Premium raw materials" title="Naturally Derived. Thoughtfully Fermented." copy="The presentation features plant-derived ingredients. Confirm the complete authorised formula and exact ingredient naming on the market label."/><div className="ingredient-grid"><motion.article whileHover={{scale:1.02}}><Image src="/images/garlic-product.jpg" alt="Garlic and BIO N:OV product imagery" fill/><div><span>Fermented ingredient</span><h3>Fermented Garlic Extract</h3><p>A plant-derived ingredient featured in the BIO N:OV presentation.</p></div></motion.article><motion.article whileHover={{scale:1.02}}><Image src="/images/lettuce-product.jpg" alt="Lettuce and BIO N:OV product imagery" fill/><div><span>Fermented ingredient</span><h3>Fermented Lettuce Extract</h3><p>A leafy plant ingredient presented as part of the fermentation concept.</p></div></motion.article><motion.article whileHover={{scale:1.02}} className="ingredient-brand"><FlaskConical/><h3>Naturally Fermented Ingredients</h3><p>Microbial fermentation is central to the product’s technology story.</p></motion.article></div></Reveal>

    <Reveal id="benefits" className="section"><Heading eyebrow="Five wellness pillars" title="Wellbeing, Viewed as a Whole"/><div className="pillars">{pillars.map(([a,b,Icon])=><motion.article whileHover={{y:-8}} key={a as string}><Icon/><h3>{a as string}</h3><p>{b as string}</p><button>Learn more <ArrowRight/></button></motion.article>)}</div></Reveal>

    <Reveal className="vessel-section"><Heading light eyebrow="An elegant visual model" title="Nitric Oxide and Normal Blood-Vessel Function" copy="Nitric oxide acts as a signalling molecule involved in normal vasodilation, helping blood vessels relax as part of healthy circulatory function."/><div className="vessels"><div><span>Narrower vessel</span><div className="vessel narrow">{[1,2,3,4].map(n=><i key={n}/>)}</div><small>Illustrative slower particle flow</small></div><div><span>Relaxed vessel</span><div className="vessel relaxed">{[1,2,3,4,5,6].map(n=><i key={n}/>)}</div><small>Illustrative smoother particle flow</small></div></div></Reveal>

    <Reveal id="team" className="section team"><Heading eyebrow="People behind the presentation" title="Science & Research Team" copy="Names and affiliations below are transcribed from the supplied PDF and require verification before public use."/><div className="research-grid">{researchers.map(([name,org,role,img])=><article key={name}><Image src={`/images/${img}`} alt={`Portrait of ${name}`} width={220} height={220}/><div><h3>{name}</h3><span>{org}</span><p>{role}</p></div></article>)}</div><div className="warning">Professional titles, affiliations and research information should be verified before publication.</div></Reveal>

    <Reveal id="product" className="product-section"><div className="showcase"><motion.div className="showcase-image" animate={{y:[0,-10,0],rotateY:[-3,3,-3]}} transition={{duration:7,repeat:Infinity,ease:"easeInOut"}}><Image src="/images/product-showcase.jpg" alt="BIO N:OV package, blister and tablet presentation" width={1920} height={1080}/></motion.div><div className="showcase-copy"><span className="eyebrow">Product showcase</span><h2>BIO N:OV</h2><div className="specs"><span>500 mg × 60 tablets</span><span>30 g</span></div><div className="tabs">{["Product Overview","Ingredients","Technology","How to Use","Safety Information"].map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}>{x}</button>)}</div><div className="tab-content">{[
      "A fermentation-based wellness product presented to support the body’s natural nitric oxide pathways.",
      "Featured ingredients include fermented garlic and fermented lettuce. Verify the complete authorised ingredient list.",
      "The PDF describes proprietary microbial fermentation technology. Patent, strain and GMP details require verification.",
      "Use only according to the authorised product label.",
      "Consult a qualified healthcare professional when appropriate. Do not use this product as a substitute for medical treatment."
    ][tab]}</div><a className="button primary" href="#contact">Request product information <ArrowRight/></a></div></div></Reveal>

    <Reveal className="section"><Heading eyebrow="Experience framework" title="Stories Shared with Care"/><div className="testimonial"><div className="quote">“</div><p>Sample testimonial layout — replace with verified customer reviews.</p><div className="dots"><i/><i/><i/></div></div></Reveal>

    <Reveal id="faq" className="section faq"><Heading eyebrow="Clear answers" title="Frequently Asked Questions"/><div className="faq-list">{faq.map((x,i)=><article key={x.question}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}><span>{x.question}</span><ChevronDown className={openFaq===i?"rotate":""}/></button>{openFaq===i&&<motion.p initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}}>{x.answer}</motion.p>}</article>)}</div></Reveal>

    <Reveal id="contact" className="contact"><div><Heading light eyebrow="Start a conversation" title="Contact the BIO N:OV Team" copy="Use this form for distributor, product or scientific enquiries. Official contact details should be added before launch."/><div className="contact-placeholder"><p><span>Official distributor</span>To be confirmed</p><p><span>Email</span>To be confirmed</p><p><span>Phone</span>To be confirmed</p><p><span>Business address</span>To be confirmed</p></div></div><form onSubmit={e=>e.preventDefault()}><div className="form-grid"><label>Full name<input required placeholder="Your name"/></label><label>Email<input type="email" required placeholder="name@example.com"/></label><label>Phone<input type="tel" placeholder="Country code + number"/></label><label>Country<input placeholder="Your country"/></label></div><label>Product enquiry<select defaultValue=""><option value="" disabled>Select an enquiry</option><option>Product information</option><option>Distribution</option><option>Science and research</option><option>Other</option></select></label><label>Message<textarea rows={5} placeholder="How can we help?"/></label><label className="consent"><input type="checkbox" required/> I consent to the processing of my information for this enquiry.</label><button className="button primary">Send enquiry <ArrowRight/></button></form></Reveal>

    <footer><div className="footer-top"><div><a href="#home" className="brand"><span className="brand-mark">V</span><span>BIO N:OV</span></a><p>Clearing the Way to Optimum Health</p></div><div><b>Explore</b>{nav.slice(1,6).map(([a,b])=><a href={`#${b}`} key={b}>{a}</a>)}</div><div><b>Information</b><a href="#product">Product</a><a href="#faq">FAQ</a><a href="#">Privacy Policy</a><a href="#">Terms & Conditions</a><a href="#">Cookie Policy</a></div><div><b>Contact</b><span>Official details to be confirmed</span><span>Social links to be confirmed</span></div></div><div className="medical-disclaimer">This website provides general educational and product information only. It is not intended as medical advice, diagnosis or treatment. Results may vary. Always follow the authorised product label and consult a qualified healthcare professional when appropriate.</div><div className="copyright">© {new Date().getFullYear()} BIO N:OV. All rights reserved. Website content requires regulatory approval before publication.</div></footer>
  </main>;
}
